In [1]:
import pandas as pd

# Descriptive Analysis Overview

In [2]:
data = pd.read_csv('./data/converted_test_2020_06_16_09-31-01.csv')
data

,Unnamed: 0,Request_Date,Flight_Date,Duration_Time,Departure_hour,flight_unique_id,route_abb,flight_number,Price,Currency,price_in_eur,Request_Weekday,Request_AM_PM
0,0,2019-07-28 11:00:00,2019-07-29 18:00:00,31.0,18,2019-07-29 FR 146,SXF-STN,FR 146,73.43,€,73.43,Sunday,AM
1,1,2019-07-28 11:00:00,2019-07-29 22:00:00,35.0,22,2019-07-29 FR 8545,SXF-STN,FR 8545,180.53,€,180.53,Sunday,AM
2,2,2019-07-28 11:00:00,2019-07-30 06:00:00,43.0,6,2019-07-30 FR 144,SXF-STN,FR 144,61.19,€,61.19,Sunday,AM
3,3,2019-07-28 23:00:00,2019-07-30 06:00:00,31.0,6,2019-07-30 FR 144,SXF-STN,FR 144,73.43,€,73.43,Sunday,PM
4,4,2019-07-28 11:00:00,2019-07-30 10:00:00,47.0,10,2019-07-30 FR 8543,SXF-STN,FR 8543,180.53,€,180.53,Sunday,AM
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5119,5119,2019-07-31 23:00:00,2019-09-10 10:00:00,971.0,10,2019-09-10 FR 8543,SXF-STN,FR 8543,35.69,€,35.69,Wednesday,PM
5120,5120,2019-08-01 11:00:00,2019-09-10 10:00:00,959.0,10,2019-09-10 FR 8543,SXF-STN,FR 8543,35.69,€,35.69,Thursday,AM
5121,5121,2019-08-01 23:00:00,2019-09-10 10:00:00,947.0,10,2019-09-10 FR 8543,SXF-STN,FR 8543,46.83,€,46.83,Thursday,PM
5122,5122,2019-08-02 11:00:00,2019-09-10 10:00:00,935.0,10,2019-09-10 FR 8543,SXF-STN,FR 8543,46.83,€,46.83,Friday,AM
5123,5123,2019-08-02 23:00:00,2019-09-10 10:00:00,923.0,10,2019-09-10 FR 8543,SXF-STN,FR 8543,39.69,€,39.69,Friday,PM

In [5]:
# Analysis of currency_in_eur column
data['price_in_eur'].describe()

count    5124.000000
mean       81.959860
std        54.300814
min        11.713473
25%        39.969275
50%        70.105380
75%       110.070000
max       311.090000
Name: price_in_eur, dtype: float64

In [6]:
# Analysis of price_in_eur column per route_abb
print(data.groupby(['route_abb']).mean())
print(data.groupby(['route_abb']).std())

            Unnamed: 0  Duration_Time  Departure_hour       Price  \
route_abb
FRA-STN    2484.061356     512.469322       12.326157   87.825662
STN-FRA    2591.697442     529.566185       13.353726   74.317542
STN-SXF    2654.796599     542.209068       12.521411   73.676108
SXF-STN    2500.983607     513.765222       13.627049  100.096470

           price_in_eur
route_abb
FRA-STN       87.825662
STN-FRA       67.697934
STN-SXF       67.095134
SXF-STN      100.096470
            Unnamed: 0  Duration_Time  Departure_hour      Price  price_in_eur
route_abb
FRA-STN    1482.712724     271.157972        5.730493  49.575164     49.575164
STN-FRA    1440.604805     261.715513        5.729570  48.292569     44.036920
STN-SXF    1447.336558     263.273626        6.326960  61.169590     55.685505
SXF-STN    1522.406224     278.957414        6.418770  54.309084     54.309084

In [8]:
# Analysis of price_in_eur column per date
print(data.groupby(['Flight_Date']).mean())
print(data.groupby(['Flight_Date']).std())

                     Unnamed: 0  Duration_Time  Departure_hour       Price  \
Flight_Date
2019-07-29 18:00:00         0.0      31.000000            18.0   73.430000
2019-07-29 22:00:00         1.0      35.000000            22.0  180.530000
2019-07-30 06:00:00         2.5      37.000000             6.0   67.310000
2019-07-30 10:00:00         4.5      41.000000            10.0  180.530000
2019-07-30 18:00:00         7.0      43.000000            18.0  152.990000
...                         ...            ...             ...         ...
2019-09-09 19:00:00      5046.0     974.171429            19.0   33.188286
2019-09-09 22:00:00      5069.5     977.000000            22.0   64.230000
2019-09-10 06:00:00      5087.5     985.000000             6.0   25.857500
2019-09-10 07:00:00      5105.5     986.000000             7.0   29.570000
2019-09-10 10:00:00      5117.5     989.000000            10.0   33.948333

                     price_in_eur
Flight_Date
2019-07-29 18:00:00     73.430000
2019-07-29 22:00:00    180.530000
2019-07-30 06:00:00     67.310000
2019-07-30 10:00:00    180.530000
2019-07-30 18:00:00    152.990000
...                           ...
2019-09-09 19:00:00     30.219709
2019-09-09 22:00:00     64.230000
2019-09-10 06:00:00     25.225383
2019-09-10 07:00:00     26.942992
2019-09-10 10:00:00     33.948333

[269 rows x 5 columns]
                     Unnamed: 0  Duration_Time  Departure_hour      Price  \
Flight_Date
2019-07-29 18:00:00         NaN            NaN             NaN        NaN
2019-07-29 22:00:00         NaN            NaN             NaN        NaN
2019-07-30 06:00:00    0.707107       8.485281             0.0   8.654987
2019-07-30 10:00:00    0.707107       8.485281             0.0   0.000000
2019-07-30 18:00:00    1.000000      12.000000             0.0   0.000000
...                         ...            ...             ...        ...
2019-09-09 19:00:00   10.246951      42.612816             0.0   3.571578
2019-09-09 22:00:00    3.605551      43.266615             0.0   6.270972
2019-09-10 06:00:00    7.071068      42.315585             0.0  13.246160
2019-09-10 07:00:00    3.605551      43.266615             0.0   2.130711
2019-09-10 10:00:00    3.605551      43.266615             0.0   9.009621

                     price_in_eur
Flight_Date
2019-07-29 18:00:00           NaN
2019-07-29 22:00:00           NaN
2019-07-30 06:00:00      8.654987
2019-07-30 10:00:00      0.000000
2019-07-30 18:00:00      0.000000
...                           ...
2019-09-09 19:00:00      3.192809
2019-09-09 22:00:00      6.270972
2019-09-10 06:00:00     13.822976
2019-09-10 07:00:00      2.056301
2019-09-10 10:00:00      9.009621

[269 rows x 5 columns]